# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
version = "1.0"
extra = false
ident = "Rocket"

[debug]
version = "2.0"
address = "127.0.0.1"
port = 8080
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "0.0.0.0"
port = 80
workers = 12
keep_alive = 5
log_level = "critical"
